[theme]
base                    = "light"
primaryColor            = "#1e5eff"
backgroundColor         = "#f7f9fc"
secondaryBackgroundColor= "#ffffff"
textColor               = "#0f172a"
font                    = "sans serif"

[client]
toolbarMode = "minimal"
